name: Python wersion
on: [push]
jobs:
  First-github-actions:
    runs-on: ubuntu-latest
    steps:
    - run: python --version
    - run: |
         python -m pip install --upgrade pip
            pip install pylint
            pytest pylint -k test_functional
